# Generated by Django 4.1.7 on 2023-02-26 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo de actor-actriz', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sinopsis', models.TextField(help_text='Resumen de la pelicula', max_length=1000)),
                ('cast', models.ManyToManyField(help_text='Ingrese actior-actriz principal, sino esta agregar en Cast', to='catalog.cast')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Género de la película', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Idioma', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FilmInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Id de esta película', primary_key=True, serialize=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('c', 'Cartelera'), ('e', 'Estreno'), ('s', 'Salio de cartelera'), ('n', 'Comming soon')], default='m', help_text='Disponibilidad', max_length=1)),
                ('location', models.CharField(blank=True, choices=[('a', 'Abasto'), ('p', 'Palermo'), ('r', 'Recoleta'), ('l', 'Lanus')], default='c', help_text='Donde ver la pelicula', max_length=1)),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.film')),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(help_text='Seleccione un genero para el libro', to='catalog.genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.ManyToManyField(help_text='Seleccionar el idioma', to='catalog.language'),
        ),
    ]
