# Generated by Django 4.1.7 on 2023-02-26 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_film_cast_alter_film_genre_alter_film_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filminstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Id unico de esta copia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filminstance',
            name='location',
            field=models.CharField(blank=True, choices=[('a', 'Abasto'), ('p', 'Palermo'), ('r', 'Recoleta'), ('l', 'Lanus')], default='a', help_text='Donde se proyecta el film', max_length=1),
        ),
        migrations.AlterField(
            model_name='filminstance',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'En cartelera'), ('e', 'Estreno'), ('s', 'Fuera de cartelera'), ('n', 'Comming soon')], default='s', help_text='Estado', max_length=1),
        ),
    ]
